### ISSUE TITLE
Manual testing

### ISSUE THREAD

**Issue by Amani215** [BME-MIT-IET/iet-hf-2022-en-muck#15]
Manual testing of certain features. No need to test everything, just add new meaningful tests if you find some important ones missing or upgrade existing tests in the project we're working on.

**Comment by MehdiMoazami** [comment]
sparse matrix test is optimised and clarified , it checks the coefficient matrix and sorting then initialisation of sparse matrix and its correctness

**Comment by Amani215** [comment]
I think the documentation looks fine. You can start a pull request and the others can review it with us.

**Comment by MehdiMoazami** [comment]
There’s a pull request already … 
I changed its name so that its more clear
